name: Code Standards

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  code-standards:
    runs-on: ubuntu-latest

    name: Code Standards

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          extensions: json, curl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run coding standards check
        run: composer cs:check