name: Unit Tests

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.5"]

    name: Unit PHP ${{ matrix.php-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: json, curl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run unit tests
        run: composer test:unit